config/routes.rb
Quiz::Application.routes.draw do
  resources :comments

  devise_for :users
  resources :ideas
  root :to => "ideas#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :idea
end

app/models/idea.rb
class Idea < ActiveRecord::Base
has_many :comments, dependent: :destroy
belongs_to :user



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :ideas
def full_name
  if first_name || last_name
    "#{first_name} #{last_name}".squeeze.strip
  else
    email
  end
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  resources :ideas, only: [:new, :index, :create, :show, :edit, :destroy] do 
    resources :comments 
  end
def create 
  @comment = @idea.comments.new(comment_attributes)
  @comment.user = current_user

  #@comment = Comment.new(params[:comment])
  #@idea = Idea.find params[:user_id]
  #@comment = @idea.comment.new(comment_attributes)
 if @comment.save
 redirect_to "/", notice: "Comment added!"
 else 
 render "/ideas/show" 

end
end

private
def comment_attributes
  params.require(:comment).permit([:body])
end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea=Idea.find(params[:id])
    @comment = Comment.new( :idea => @idea )
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    
    @idea = Idea.new(idea_params)
      if @idea.save
         redirect_to @idea, notice: 'Idea was successfully created.' 
         
      else
         render action: 'new' 
        
     
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    
      if @idea.update(idea_params)
         redirect_to "/", notice: 'Idea was successfully updated.' 
         
      else
        render action: 'edit' 
         
      
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
      if @idea.destroy
       redirect_to ideas_url 
    end   
    
  end
 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Listing ideas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>
<div>
<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>
<p> Add a Comment </p>
<%= form_for @comment do |f| %>
  <%=f.text_area :body %>
  <%= f.submit "Submit" %>
  <% end %>
</div>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz</title>
  <link href="css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="container">
  <nav class="nav-main">
    <% if user_signed_in? %>
   
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  
  <% else %>
   
    <%= link_to("Login", new_user_session_path) %> 
    
    <% end %> 
    <a href="/" class= "btn btn-default"> Home </a>
    

    
    </div>
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>
 